/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.


const config ={
    identityPoolId:     "ap-south-1:61d68fc7-419f-4f8d-a73b-cb9dc1984d81",
    region:'ap-south-1',
    userPoolId: 'ap-south-1_TVnumIJAd',
    userPoolWebClientId:'3m7473kkklmlngh059i70n9m3u'
}


export default config;
